stages:
# - build
# - test
- publish
# - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_JOB_ID

# bot_tests:
#   stage: test
#   image: python
#   script:
#     - pip install -r ./tests/requirements.txt 
#     - pytest ./

docker_publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_ACCESS_TOKEN
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

# bot_deploy:
#   image: alpine:latest
#   stage: deploy
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_ACCESS_TOKEN"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker rm -f bot"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d --network="host" --name="bot" $TAG_COMMIT"
