stages:
  - build
  - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip

build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

deploy:
  stage: deploy
  script:
    - source venv/bin/activate
    - python your_bot_script.py
